// Generates the derived documentation pages from the data files, so every number has one home.
//   data/migancore-public.en.json  (falls back to .id.json)  -> docs/experiments.md, docs/lineage.md
//   data/lineage.en.json                                      -> docs/lineage.md
//   data/timeline.en.json                                     -> docs/timeline.md
// Do not edit the generated pages by hand; edit the data and run:  node tools/build-docs.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const readJson = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8'));
const enPath = 'data/migancore-public.en.json';
const data = fs.existsSync(path.join(ROOT, enPath)) ? readJson(enPath) : readJson('data/migancore-public.id.json');
const isEnglish = fs.existsSync(path.join(ROOT, enPath));
const lineageEn = readJson('data/lineage.en.json');
const timeline = readJson('data/timeline.en.json');

const t = (obj, key) => obj[key] ?? obj[key + '_id'] ?? '';
const STATE = { lulus: 'pass', gagal: 'fail', netral: 'neutral', belum: 'not run' };
const STATE_ICON = { lulus: '🟢', gagal: '🔴', netral: '🟡', belum: '🟣' };
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const firstSentence = (s, n = 200) => {
  const clean = String(s ?? '').replace(/\*\*/g, '');
  return clean.length <= n ? clean : clean.slice(0, n).replace(/\s+\S*$/, '') + ' …';
};
const HEADER = (title) => `# ${title}\n\n> Generated by \`tools/build-docs.mjs\` from the files in [\`data/\`](../data/). ` +
  `Do not edit by hand.${isEnglish ? '' : ' (English data not present yet: text shown in Indonesian.)'}\n\n`;

// ---------- experiments.md
{
  const pr = [...data.preRegistrations].sort((a, b) => String(a.date ?? '9999').localeCompare(String(b.date ?? '9999')));
  const counts = data.counts.verdictStates;
  let md = HEADER('Experiment register — 39 pre-registrations and their verdicts');
  md += `Each experiment was pre-registered in a JSON file under [\`flywheel/\`](../flywheel/) before any data existed: ` +
    `hypothesis, metric, thresholds, stopping rule and forecasts, locked by a git commit. The verdict below is the ` +
    `verdict field of that file, written back by the verdict tool. States: ` +
    `${STATE_ICON.lulus} pass ${counts.lulus} · ${STATE_ICON.gagal} fail ${counts.gagal} · ` +
    `${STATE_ICON.netral} neutral ${counts.netral} (includes invalid instruments and experiments stopped before running) · ` +
    `${STATE_ICON.belum} not run ${counts.belum}.\n\n`;
  md += `![Verdict mosaic](img/infographics/03-verdict-mosaic.svg)\n\n`;
  md += `| Date | Experiment | State | Verdict (start) |\n|---|---|---|---|\n`;
  for (const p of pr) {
    md += `| ${p.date ?? '—'} | [\`${p.id}\`](../flywheel/PRA-DAFTAR-${p.id}.json) — ${esc(t(p, 'title'))} | ` +
      `${STATE_ICON[p.state] ?? ''} ${STATE[p.state] ?? p.state} | ${esc(firstSentence(t(p, 'verdict')))} |\n`;
  }
  md += `\n## Full verdicts\n\n`;
  for (const p of pr) {
    md += `<details><summary><b>${p.id}</b> — ${esc(t(p, 'title'))} (${STATE[p.state] ?? p.state}, ${p.date ?? 'no date'})</summary>\n\n`;
    md += `${t(p, 'verdict')}\n\nLocked: ${p.locked ?? '—'} · File: [\`flywheel/PRA-DAFTAR-${p.id}.json\`](../flywheel/PRA-DAFTAR-${p.id}.json)\n\n</details>\n\n`;
  }
  fs.writeFileSync(path.join(ROOT, 'docs/experiments.md'), md);
}

// ---------- lineage.md
{
  const long = Object.fromEntries((data.lineage ?? []).map((l) => [l.no, l]));
  let md = HEADER('Lineage — 41 model variants, one served model');
  md += `Every variant that was trained, named or planned, from a small pre-Qwen3 family to the candidates that ` +
    `were never born. **A higher version number does not mean a better model**; the status comes from verdicts.\n\n`;
  md += `![Lineage](img/infographics/06-lineage.svg)\n\n`;
  md += `| # | Variant | Date | Base | Family | Status | Note |\n|---|---|---|---|---|---|---|\n`;
  for (const e of lineageEn.entries) {
    md += `| ${e.no} | \`${esc(e.name)}\` | ${esc(e.date)} | ${esc(e.base)} | ${esc(lineageEn.families[e.family] ?? e.family)} | ` +
      `**${esc(e.status)}** | ${esc(e.note)} |\n`;
  }
  md += `\n### Status legend\n\n` + Object.entries(lineageEn.statuses).map(([k, v]) => `- **${k}** — ${v}`).join('\n') + '\n';
  md += `\n## Per-variant detail\n\nLong fields come from the lineage reference (goal, data and method, measurement, verdict).\n\n`;
  for (const e of lineageEn.entries) {
    const l = long[e.no];
    md += `### ${e.no}. \`${e.name}\`\n\n`;
    if (!l) { md += `${e.note}\n\n`; continue; }
    const row = (label, key) => { const v = t(l, key); return v ? `- **${label}:** ${v}\n` : ''; };
    md += row('Date and base', 'dateAndBase') + row('Goal', 'goal') + row('Data, method, cost', 'dataMethod') +
      row('Measured', 'measured') + row('Verdict / status', 'verdict') + '\n';
  }
  fs.writeFileSync(path.join(ROOT, 'docs/lineage.md'), md);
}

// ---------- timeline.md
{
  let md = HEADER('Timeline — one month of decisions (29 Aug – 28 Sep 2026)');
  md += `![Timeline](img/infographics/04-timeline.svg)\n\n`;
  for (const ev of timeline.events) {
    const refs = ev.refs.length ? ` Verdicts: ${ev.refs.map((r) => `[\`${r}\`](../flywheel/PRA-DAFTAR-${r}.json)`).join(', ')}.` : '';
    md += `### ${ev.date} — ${ev.title}\n\n${ev.detail}${refs}\n\n`;
  }
  fs.writeFileSync(path.join(ROOT, 'docs/timeline.md'), md);
}

console.log(`docs generated (${isEnglish ? 'English' : 'Indonesian fallback'} data): experiments.md, lineage.md, timeline.md`);
